# SPDX-FileCopyrightText: 2021 the netsim authors
#
# SPDX-License-Identifier: MIT

builds:
  - main: ./cmd/netsim
    binary: netsim
    goos:
      - linux
      # - windows # we use a .sh as an essential component; so windows will only work under WSL
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    wrap_in_directory: true
    files:
        - README.md
        - docs/tutorial.md
        - docs/commands.md
        - LICENSE
        # - ssb-fixtures/
